name: Build Windows Application

on:
  push:
    branches: [ main, shorebird ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
    
    - name: Setup Shorebird CLI
      uses: shorebirdtech/setup-shorebird@v1
    
    - name: Set Shorebird Token
      run: echo "SHOREBIRD_TOKEN=${{ secrets.SHOREBIRD_TOKEN }}" >> $env:GITHUB_ENV
      shell: powershell
    
    - name: Configure Git for long paths
      run: git config --system core.longpaths true
    
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Initialize Shorebird app (if needed)
      run: |
        if (!(Test-Path "shorebird.yaml")) {
          shorebird init --force --display-name "POS UI Flutter"
        } else {
          Write-Host "shorebird.yaml already exists, checking app..."
          $appExists = shorebird apps list 2>&1 | Select-String "pos-ui-flutter"
          if (!$appExists) {
            Write-Host "Creating Shorebird app..."
            shorebird apps create --display-name "POS UI Flutter"
          }
        }
      shell: powershell
    
    - name: Build Windows with Shorebird (Release)
      run: shorebird release windows --no-confirm
    
    - name: List build outputs
      shell: pwsh
      run: |
        Write-Host "Listing build/windows:"
        if (Test-Path build/windows) {
          Get-ChildItem -Recurse build/windows | ForEach-Object { $_.FullName }
        } else {
          Write-Host "build/windows does not exist"
        }
    
    - name: Find Shorebird Release directory
      id: find_release
      shell: pwsh
      run: |
        $candidates = @(
          "build/windows/x64/runner/Release",
          "build/windows/runner/Release"
        )
        $found = $false
        foreach ($p in $candidates) {
          if (Test-Path $p) {
            Write-Host "Found release dir: $p"
            "release_dir=$p" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            $found = $true
            break
          }
        }
        if (-not $found) {
          Write-Error "Release directory not found."
          exit 1
        }
    
    - name: Zip artifact
      shell: pwsh
      run: |
        $src = "${{ steps.find_release.outputs.release_dir }}"
        $zip = "windows-build.zip"
        Write-Host "Zipping $src to $zip"
        if (Test-Path $zip) { Remove-Item $zip -Force }
        Compress-Archive -Path "$src/*" -DestinationPath $zip
        Write-Host "Done."
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: windows-build.zip
        retention-days: 30 